image:
  - Visual Studio 2015
  - Ubuntu

environment:
  PERL5LIB: /home/appveyor/perl5/lib/perl5

platform: x64

branches:
  only:
    - master

skip_tags: true

install:
  - cmd: if not exist "C:\strawberry" cinst strawberryperl
  - cmd: set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cmd: cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - sh: sudo apt-get install build-essential git libssl-dev
  - sh: sudo apt-get install -y perl
  - sh: export PATH=/home/appveyor/perl5/bin:$PATH
  - perl -v
  - cpan App::cpanminus
  - cpanm --installdeps .

build_script:
  - perl Makefile.PL
  - cmd: gmake test
  - sh: make test
