# brian's standard Appveyor config for Perl 5 modules
# https://github.com/briandfoy/brians_perl_modules_appveyor_config
# This file is licensed under the Artistic License 2.0

image:
  - Visual Studio 2019
  - ubuntu

environment:
  PERL5LIB: /home/appveyor/perl5/lib/perl5
  matrix:
    - perl: strawberryperl
      make: gmake
    - perl: cygwinperl
      make: make
    - perl: perl
      make: make
platform: x64

branches:
  only:
    - master
    - appveyor

skip_tags: true

install:
  - cmd: if %perl%==strawberryperl ( if not exist "C:\strawberry" cinst strawberryperl )
  - cmd: if %perl%==strawberryperl perl -V
  - cmd: if %perl%==strawberryperl set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cmd: if %perl%==strawberryperl cpan -M http://www.cpan.org -T LWP::Protocol::https
  - cmd: if %perl%==strawberryperl cpan -M http://www.cpan.org -T ExtUtils::MakeMaker
  - cmd: if %perl%==strawberryperl cpan -M http://www.cpan.org -T .
  - cmd: if %perl%==cygwinperl     c:\cygwin\bin\sh -c "perl -MConfig -le 'print qq(OSNAME: $Config{osname})'"
  - cmd: if %perl%==cygwinperl     c:\cygwin\bin\sh -c "/usr/bin/perl -V"
  - cmd: if %perl%==cygwinperl     c:\cygwin\setup-x86.exe -q --packages=libcrypt-devel
  - cmd: if %perl%==cygwinperl     c:\cygwin\bin\sh -c "PATH=/usr/bin:/bin; (cd /tmp && git clone https://github.com/eserte/travis-helper-cpan-pm.git && ./travis-helper-cpan-pm/travis-helper-cpan-pm --no-sudo)"
  - cmd: if %perl%==cygwinperl     c:\cygwin\bin\sh -c "PATH=/usr/bin:/bin; cpan -M http://www.cpan.org -T LWP::Protocol::https"
  - cmd: if %perl%==cygwinperl     c:\cygwin\bin\sh -c "PATH=/usr/bin:/bin; cpan -M http://www.cpan.org -T ExtUtils::MakeMaker"
  - cmd: if %perl%==cygwinperl     c:\cygwin\bin\sh -c "PATH=/usr/bin:/bin; cpan -M http://www.cpan.org -T ."
  - cmd: if %perl%==strawberryperl cpan -M http://www.cpan.org -T .
  - cmd: if %perl%==cygwinperl     c:\cygwin\bin\sh -c "PATH=/usr/bin:/bin; cpan -M http://www.cpan.org -T ."
  - sh:  if [ ${perl} = "perl" ]; then sudo apt-get update; fi
  - sh:  if [ ${perl} = "perl" ]; then sudo env DEBIAN_FRONTEND=noninteractive apt-get -yq install build-essential git libssl-dev; fi
  - sh:  if [ ${perl} = "perl" ]; then sudo apt-get install -y perl; fi
  - sh:  if [ ${perl} = "perl" ]; then export PATH=/home/appveyor/perl5/bin:$PATH; fi
  - sh:  if [ ${perl} = "perl" ]; then perl -v; fi
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - sh:  cd $APPVEYOR_BUILD_FOLDER


build_script:
  - cmd: if %perl%==cygwinperl     c:\cygwin\bin\sh -c "PATH=/usr/bin:/bin; cpan -t ."
  - cmd: if %perl%==strawberryperl ( perl Makefile.PL && %make% test )
  - sh:  if [ ${perl} = "perl" ]; then perl Makefile.PL && $make test; fi
